//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crazypizza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carousel
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public int ProdutoID { get; set; }
        public Nullable<bool> Destaque { get; set; }
        public string Imagem { get; set; }
    
        public virtual Produtos Produtos { get; set; }
    }
}
